"""Widen `accounts.username` from 64 to 255 characters.

A Cloudflare-identified caller's account is keyed on its username, and that username IS the verified
email address (`core/auth/cloudflare_identity.py`). RFC 5321 allows an address up to 254 characters,
so a 64-character column silently caps what can be stored. SQLite ignores `VARCHAR` length while
Postgres enforces it, so without this the failure would appear only in a hosted deployment, as a 500
on account creation for a caller who did nothing wrong.

WHY raw, dialect-guarded SQL instead of the declarative `ops.AlterField`:

SQLite cannot widen a column in place, so Tortoise's SQLite editor rebuilds the table —
`CREATE TABLE new__accounts` … `DROP TABLE accounts` … `RENAME`. `oauth_connections.account_id`
references `accounts` with `ON DELETE CASCADE`, so that `DROP` **deletes every OAuth connection in
the database**. `test_migration_populated_db` catches it: the connection row seeded before the
upgrade is gone afterwards.

And the rebuild buys nothing, because SQLite does not enforce `VARCHAR(n)` at all — the column
already stores a 254-character address. So the correct operation is genuinely dialect-specific: DDL
on Postgres, nothing on SQLite. This is not a workaround for the cascade; the cascade is what
exposed that the SQLite branch never needed DDL in the first place.

CONSEQUENCE to know when adding the next migration: `RunPython` contributes no state change, so
Tortoise's migration state still records `max_length=64` while the model declares 255. Nothing at
runtime reads that state — these migrations are hand-written, and `python -m tortoise migrate` only
applies them — but an autogenerated migration would propose this same widening again. Delete that
proposal rather than applying it twice.
"""

from tortoise import migrations
from tortoise.migrations import operations as ops

_POSTGRES_DIALECTS = frozenset({"postgres", "postgresql", "asyncpg", "psycopg"})


async def _alter(schema_editor, width: int) -> None:
    """Run the widening on Postgres only; every other dialect is left untouched."""
    if schema_editor is None:  # pragma: no cover - defensive, mirrors ops.RunPython's own guard
        return
    dialect = getattr(getattr(schema_editor, "client", None), "capabilities", None)
    dialect_name = getattr(dialect, "dialect", "") or ""
    if dialect_name.lower() not in _POSTGRES_DIALECTS:
        return
    await schema_editor._run_sql(  # noqa: SLF001 - the editor exposes no public raw-SQL entry point
        f'ALTER TABLE "accounts" ALTER COLUMN "username" TYPE VARCHAR({width})'
    )


async def forwards(_apps, schema_editor) -> None:
    await _alter(schema_editor, 255)


async def backwards(_apps, schema_editor) -> None:
    """Narrowing is lossy by definition — it fails on Postgres if any stored address exceeds 64.

    Left as the honest inverse rather than a silent truncation: a rollback that quietly rewrote
    people's usernames would detach them from their stored credentials.
    """
    await _alter(schema_editor, 64)


class Migration(migrations.Migration):
    dependencies = [("models", "0007_connection_auth_type")]

    operations = [ops.RunPython(forwards, backwards)]
