{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aigateway.fullname" . }}
  labels:
    {{- include "aigateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aigateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.config.port }}
      {{- if .Values.networkPolicy.ingressCIDRs }}
      from:
        {{- range .Values.networkPolicy.ingressCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      {{- end }}
  egress:
    - {}
{{- end }}
