"""url4_streaming_protocol — CloudEvents 1.0 + OTel frame contract (docs/protocol.md)."""

from url4_streaming_protocol.envelope import CloudEvent
from url4_streaming_protocol.signals import (
    AttachData,
    CostUsageData,
    HeartbeatData,
    LogData,
    ResultData,
    SpanData,
    StartedData,
    StopData,
    TerminatedData,
)
from url4_streaming_protocol.taxonomy import CostBreakdown, ErrorInfo, TokenUsage
from url4_streaming_protocol.unions import (
    AttachEvent,
    CostUsageEvent,
    Frame,
    FrameAdapter,
    HeartbeatEvent,
    InboundFrame,
    InboundFrameAdapter,
    LogEvent,
    OutboundFrame,
    OutboundFrameAdapter,
    ResultEvent,
    SpanEvent,
    StartedEvent,
    StopEvent,
    TerminatedEvent,
)

__all__ = [
    "AttachData",
    "AttachEvent",
    "CloudEvent",
    "CostBreakdown",
    "CostUsageData",
    "CostUsageEvent",
    "ErrorInfo",
    "Frame",
    "FrameAdapter",
    "HeartbeatData",
    "HeartbeatEvent",
    "InboundFrame",
    "InboundFrameAdapter",
    "LogData",
    "LogEvent",
    "OutboundFrame",
    "OutboundFrameAdapter",
    "ResultData",
    "ResultEvent",
    "SpanData",
    "SpanEvent",
    "StartedData",
    "StartedEvent",
    "StopData",
    "StopEvent",
    "TerminatedData",
    "TerminatedEvent",
    "TokenUsage",
]
